//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        public int id { get; set; }
        public string KategoriBaslik { get; set; }
        public string KategoriLink { get; set; }
        public string tip { get; set; }
    }
}
