//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVTemplate.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelDB : DbContext
    {
        public ModelDB()
            : base("name=ModelDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Referans> Referans { get; set; }
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<Deneyim> Deneyim { get; set; }
        public virtual DbSet<DilBilgi> DilBilgi { get; set; }
        public virtual DbSet<Egitim> Egitim { get; set; }
        public virtual DbSet<Proje> Proje { get; set; }
        public virtual DbSet<ProjeCategory> ProjeCategory { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<AdminLogin> AdminLogin { get; set; }
        public virtual DbSet<Resimler> Resimler { get; set; }
        public virtual DbSet<Kisi> Kisi { get; set; }
        public virtual DbSet<BeceriYetenek> BeceriYetenek { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
    }
}
