//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proje
    {
        public int id { get; set; }
        public string altBaslik { get; set; }
        public string aciklama { get; set; }
        public string projeYili { get; set; }
        public string projeLinki { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual ProjeCategory ProjeCategory { get; set; }
    }
}
