//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referans
    {
        public int id { get; set; }
        public string refAd { get; set; }
        public string refSoyad { get; set; }
        public string refSirket { get; set; }
        public string refTelefon { get; set; }
        public string refGorev { get; set; }
    }
}
