//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resimler
    {
        public int id { get; set; }
        public string resimYol { get; set; }
        public Nullable<int> resimNo { get; set; }
    }
}
